### ISSUE TITLE
Password request dialog sometimes doesn't disappear when authenticated with Biometrics

### ISSUE THREAD

**Issue by cjohnsto-nz** [jamie-mh/AuthenticatorPro#365] opened 2022-01-30 07:31 UTC
S21 Ultra Exynos
Android 12

I think that there are occasionally duplicates of that dialog overlaid, and that using the fingerprint scanner only closes the most recently created one.

**Comment by dschoerk** [comment] 2022-04-22 13:51
I rarely notice that issue too on my Oneplus 8t, Android 12

**Comment by jamie-mh** [comment] 2022-05-21 08:51
This appears to be caused by switching between the app and other apps.
Can anyone confirm? Thanks.

**Comment by cjohnsto-nz** [comment] 2022-05-21 08:58
Yeah. I think it shows that dialog on activity start. The dialog should set a flag on initializing that prevents another dialog from being created.
________________________________

**Comment by jamie-mh** [comment] 2022-08-07 10:48
Fixed in eb0eb46.

**Closed by jamie-mh** 2022-08-07 10:48 UTC
Labels: bug
