### ISSUE TITLE
Cropped username text

### ISSUE THREAD

**Issue by haukist** [jamie-mh/AuthenticatorPro#1066] opened 2023-12-29 19:31 UTC
**Describe the bug**
Username text is cropped when System Font option is enabled. This bug only appears when View Mode is set to `Compact` or `Tile`.

**To Reproduce**
1. Go to settings and set View Mode to Compact or Tile
2. Enable System Font option
3. See under the baseline of username text
![IMG_1703874149112](https://github.com/jamie-mh/AuthenticatorPro/assets/14955895/2ca022c9-cc37-49ed-b063-4c5285417a86)

**Expected behavior**
The username text should not get cropped.

**App Version**
1.24.0

**Additional context**
Pixel 6 / Android 14

**Comment by fs2597** [comment] 2024-02-05 17:39
This isn’t actually related to the System Font option. That only seems to matter because the app’s custom font is vertically smaller than the system font at any nominal size.

The problem is visible in all view modes, whether or not the System Font option is enabled, when the system font size is increased (Android settings > Display > Display size and text > Font size).

My phone (Google Pixel 5a, Android 14) defaults to size 2/7, and I have it increased to 4/7. In the default view mode, the usernames are mostly cut off, but I can see enough of the tops of letters to figure out which one is which. In the compact and tile view modes, I don’t see usernames at all.

<img alt="authpro-usernames" src="https://github.com/jamie-mh/AuthenticatorPro/assets/118265658/b41253d3-5f3e-4a1e-bafe-9a9cd0a0bbc4" width="432" height="150" />

**Comment by jamie-mh** [comment] 2024-03-01 17:42
Fixed in 1.24.1

**Closed by jamie-mh** 2024-03-01 17:42 UTC
Labels: bug
