### ISSUE TITLE
Icon search not working after 1.20.0 update

### ISSUE THREAD

**Issue by ch3thanhs** [jamie-mh/AuthenticatorPro#778] opened 2023-05-18 09:12 UTC
**Describe the bug**
Unable to search icons.

**To Reproduce**
1. Go to change icon of any added account.
2. Search for any icon.

**Expected behavior**
The icons that match the search term should appear at the top.

**App Version**
1.20.0

**Comment by jamie-mh** [comment] 2023-05-20 06:53
Hi @ch3thanhs ,

I'm not able to reproduce this. It works fine on my end.
[device-2023-05-20-084937.webm](https://github.com/jamie-mh/AuthenticatorPro/assets/7887162/ffb6f96d-95c8-4723-bcbd-a99cf348c6ed)

Does this happen consistently or is this an irregular occurrence?

Thanks

**Comment by bluezed** [comment] 2023-05-20 07:00
I have the same issue. Mo matter what I enter the list of icons stays the same.

Here's a quick screen recording: 

https://github.com/jamie-mh/AuthenticatorPro/assets/3831765/4f7624f4-f863-4f2e-af6e-c52fea616ac0

**Comment by ch3thanhs** [comment] 2023-05-20 07:06
Hi @jamie-mh, I have tested on two of my devices, it happens consistently.

**Comment by jamie-mh** [comment] 2023-05-20 08:33
Tried it on another device. Fixed in 60c5c64.

**Closed by jamie-mh** 2023-05-20 08:33 UTC
Labels: bug
