### ISSUE TITLE
QR code do not work

### ISSUE THREAD

**Issue by gusantoscode** [jamie-mh/AuthenticatorPro#357] opened 2021-12-31 13:43 UTC
**Describe the bug**
When I try import a new key with the QR code, just not working. My camera is working perfecly, is focusing normally.

**is To Reproduce**
1. Click on more button
3. Click on scan a QR code
4. Click on scan from camera
5. And see the error, you can point at the qr code and not working.

**Expected behavior**
...

**App Version**
1.15.6

**Additional context**
...

**Comment by jamie-mh** [comment] 2022-01-01 14:39
Duplicate of #286

**Closed by jamie-mh** 2022-01-01 14:39 UTC
Labels: bug
