### ISSUE TITLE
AuthenticatorPlus import not working

### ISSUE THREAD

**Issue by id628** [jamie-mh/AuthenticatorPro#119] opened 2021-02-01 16:28 UTC
No matter what I do when I try to import my authplus.db file, I get "The password is incorrect or the file is corrupt".

I've tried the Authplus password, a blank password, etc. Is there any way to debug this?

**Comment by jamie-mh** [comment] 2021-02-02 07:40
This seems like #110 again. What version of the app are you running?

**Comment by id628** [comment] 2021-02-02 14:52
It comes up as 1.14.2

Also of note, should I be able to import the Accounts.txt file from Plus's export ZIP file using the URI list format? That doesn't work either - "The file could not be imported".

**Comment by jamie-mh** [comment] 2021-02-03 15:48
There must be something strange in your uri list that is throwing it off. Is there anything that looks out of the ordinary? If so, try removing the line and importing the uri list again.

**Comment by jamie-mh** [comment] 2021-02-08 19:58
Hi,

Is this issue still relevant, does anything need fixing? Thanks.

**Comment by id628** [comment] 2021-02-09 16:16
I tried a few edits, but ended up going with a different app that imported my list without issues.
Should it be fixed still for others? Yes. 
Unfortunately I'm not able to spend a lot of time to debug right now due to other commitments.

**Comment by Gazoo** [comment] 2021-02-11 17:52
Just a note confirming that the import from AuthenticatorPlus still isn't working. I even imported into Aegis Authenticator then exported to the plain text file from that app but AuthenticatorPro couldn't import from that export either :(

**Comment by Gazoo** [comment] 2021-02-11 19:46
OK I figured it out. Any duplicate entries that you have in your export will cause the entire import to fail.

**Comment by jamie-mh** [comment] 2021-02-11 20:42
Good find, this does indeed cause a failure. I've made some changes to address this. It never crossed my mind that you could have the same authenticator multiple times in Authenticator Plus. But, why would you though, it seems a little strange.

**Comment by Gazoo** [comment] 2021-02-11 20:46
> Good find, this does indeed cause a failure. I've made some changes to address this. It never crossed my mind that you could have the same authenticator multiple times in Authenticator Plus. But, why would you though, it seems a little strange.

I think it might just be a bug in the Authenticator Plus export. I don't remember there being duplicate entries listed in the app itself but there were a bunch in the export.

**Comment by numbawon** [comment] 2021-02-14 03:54
@Gazoo thank you for that find. I was able to clean up the export from Auth+. I can confirm, mine had a complete set duplicate of all entries when viewed in a text editor. Likely the reason the authplus.db import fails is it probably has duplicate entries in it as well, even though it does not display any duplicates in the Auth+ UI.

**Comment by gilgongo** [comment] 2021-02-17 09:17
@numbawon How did you view the db in a text editor? I've tried using DB Browser for SQLite and it doesn't seem to want to open it.

**Comment by Gazoo** [comment] 2021-02-17 14:26
@gilgongo just export it as plaintext until the fix is published. Don't use the  authplus.db format. Then you can use import it using the URI list (plain text list of otpauth URIs).

**Comment by gilgongo** [comment] 2021-02-17 14:31
@Gazoo Sorry, I meant how do I open the authplus.db so as to get the plain text? Is its SQLCipher method something non-standard? What tool did you use?

**Comment by Gazoo** [comment] 2021-02-17 14:35
@gilgongo I imported into Aegis Authenticator then exported to the plain text file.

**Comment by jamie-mh** [comment] 2021-02-25 13:06
Hi,

Is this still an issue in the latest version?

**Comment by quietmansoath** [comment] 2021-03-05 00:03
Yes. I'm getting an error that the file is not a valid authenticator pro backup file. The backup file was encrypted with a pasword but I'm not even making it to the stage where I'm being prompted for it. I made my backup with one phone, and now I'm in the process of switching phones, and I can't import any of my backups.

**Comment by quietmansoath** [comment] 2021-03-05 00:06
I just tried again, and it worked. The only difference was that this time I made the backup without a password.

**Comment by quietmansoath** [comment] 2021-03-05 00:24
I'm a noob and don't know anything about this duplicates things, but I do have multiple of the same type of account? Like various google accounts have their own codes. I've also had to delete some in the past and re-do them. They don't show up in the app but maybe they are still hidden somewhere?

**Comment by gilgongo** [comment] 2021-03-05 07:21
I tried various methods to read/import the encrypted file but none of them worked. I transferred all my accounts manually in the end.

**Comment by peschie1967** [comment] 2021-04-23 17:47
This bug seems not to be solved. Cannot import the backup.

**Comment by l-marchesi** [comment] 2021-09-20 13:37
I was able to migrate from Auth+ mid september without any of the above mentioned issues.
I did somehow lose a code while migrating (Firefox account) on one device - however I was able to recover it from a second device.

**Comment by c0deright** [comment] 2022-01-05 11:46
Importing authplus.db as of 2022 with APP version 1.15.7 worked without problems for me.

**Comment by jamie-mh** [comment] 2023-12-03 11:16
Due to the lack of activity, I'm closing this issue.

**Closed by jamie-mh** 2023-12-03 11:16 UTC
Labels: bug
