### ISSUE TITLE
A 2FA code preview for the upcoming 2FA code like the 2FA App has

### ISSUE THREAD

**Issue by Uneccessary** [jamie-mh/AuthenticatorPro#999] opened 2023-10-17 13:59 UTC
**Is your feature request related to a problem? Please describe.**
Is very inconfinient to wait a few seconds when you need to type the 2FA code, for example when you log in on PC and need to type in your 2FA code, but the 2FA code already runs out in few seconds and you will not be fast enough to type it completly and hit enter or the button.

**Describe the solution you'd like**
A preview for the upcoming 2FA code when the code is only 5s remaining, which is shown in the bottom right corner of the field, like in the 2FA App (which is rather anti-privacy, thats why I don't use it anymore) and when you click on the field it copy the upcoming 2FA code in the last 5s instead of the code which runs out in 5s or less.

**Additional context**
I would like, if you could make this as a setting since not everyone probaly want this

**Comment by Kvasenok** [comment] 2023-10-19 18:44
It's would be a great feature! I want this.

**Comment by OmarNazzal150** [comment] 2023-10-19 19:28
Yes. Me too. I Agree with Kvasenok

**Comment by ch3thanhs** [comment] 2023-10-28 06:01
Duplicate of #707

**Comment by jamie-mh** [comment] 2023-12-15 18:47
The [1.24.0 beta](https://github.com/jamie-mh/AuthenticatorPro/releases/tag/1.24.0-beta) has a "Skip to next" feature. You can now skip to the next code when the current one is close to expiring.

**Closed** 2023-12-28 19:14 UTC
Labels: enhancement
