### ISSUE TITLE
Export authenticators from Wear OS app

### ISSUE THREAD

**Issue by nicholaslimck** [jamie-mh/AuthenticatorPro#457] opened 2022-06-06 07:21 UTC
I recently factory reset my phone and forgot my backup's password. However, I have previously linked my phone app to my Wear OS watch and the authenticator still works on my watch. I think the ability to generate QR codes on the Wear OS app would be useful in such a situation so I could re-import my authenticators back to my phone.

**Comment by jamie-mh** [comment] 2022-06-06 10:08
Duplicate of #278

**Closed by jamie-mh** 2022-06-06 10:08 UTC
Labels: enhancement
