### ISSUE TITLE
[FR] Network disk backup?

### ISSUE THREAD

**Issue by magojohnji** [jamie-mh/AuthenticatorPro#1058] opened 2023-12-23 11:32 UTC
**Is your feature request related to a problem? Please describe.**
I often struggle with the hassle of manual backups.

**Describe the solution you'd like**
Using Outlook and other cloud storage for synchronization.

**Additional context**
None

**Comment by ch3thanhs** [comment] 2023-12-27 04:27
You can use an app like FolderSync to set up scheduled backups.

**Comment by jamie-mh** [comment] 2023-12-28 16:32
Duplicate of #16.

**Closed by jamie-mh** 2023-12-28 16:32 UTC
Labels: enhancement
