### ISSUE TITLE
Connect Cloud Service

### ISSUE THREAD

**Issue by gusantoscode** [jamie-mh/AuthenticatorPro#354] opened 2021-12-26 00:03 UTC
**Is your feature request related to a problem? Please describe.**
Connect Google Drive or other cloud service to automatic import backups when i change my tokens.

**Describe the solution you'd like**
.

**Additional context**
.

**Comment by jamie-mh** [comment] 2021-12-26 09:29
Duplicate of #16

**Closed by jamie-mh** 2021-12-26 09:29 UTC
Labels: enhancement
