### ISSUE TITLE
Unable to import authenticator backups that are more than 1kb

### ISSUE THREAD

**Issue by farrukh2002** [jamie-mh/AuthenticatorPro#659] opened 2023-02-16 17:23 UTC
While trying to import any backup above 1kb in file size, it is greyed out when trying to import the backup.

**Comment by farrukh2002** [comment] 2023-02-16 17:24
![Screenshot_20230216-224918_Files](https://user-images.githubusercontent.com/59789349/219441052-1c935ef2-d411-4da0-8dbe-3ca2e485162d.png)

**Comment by plainslice** [comment] 2023-02-17 18:28
Im having this same issue as well. Im kind of panicking because I just bought a new phone and cant access any of my 2FA's that I have backed up...

**Comment by jamie-mh** [comment] 2023-02-17 18:54
The hypothesis is empirically false because my backups are typically much larger than 1Kb. This seems like an issue with Google Drive specifically, notice how the files that work say "BIN file".

You could try downloading the file to the device and importing directly from local storage, perhaps?

**Comment by plainslice** [comment] 2023-02-18 14:54
> The hypothesis is empirically false because my backups are typically much larger than 1Kb. This seems like an issue with Google Drive specifically, notice how the files that work say "BIN file".
> 
> You could try downloading the file to the device and importing directly from local storage, perhaps?

Im not sure about the size hypothesis, as all mine are over that. I tried numerous backups from both drive as well as ones saved directly to my phone. Every single one is greyed out.

**Comment by ipkpjersi** [comment] 2023-02-22 17:33
This bug fix seems fairly important, I wonder if it's worth tagging a new bug fix release with the fix from a171b53317272d18c5ec1d3e2f9eb22e1f8f6250?

**Comment by jamie-mh** [comment] 2023-02-22 18:11
Yeah, I can create a release. My commit from earlier is just an idea, but I'm not able to reproduce the issue on my end. I still need to check for side effects.

**Comment by ipkpjersi** [comment] 2023-02-22 18:14
Hmm yeah that's true. I also am not able to reproduce the issue with a 17KB encrypted .authpro file on my OP10T using Android 13 or my OP7Pro using Android 11.

**Comment by jamie-mh** [comment] 2023-02-22 19:00
It's most likely a vendor specific bug, certain manufacturers have software that works in ways you don't expect.
Anyway, I've been running the changes on my device for the last few days, and it's been fine. The latest release (1.17.2) includes the change, hopefully it fixes the issue.

**Comment by jamie-mh** [comment] 2023-02-25 13:50
An outside source claims that the issue is now fixed.

**Closed by jamie-mh** 2023-02-25 13:50 UTC
Labels: bug

**Comment by plainslice** [comment] 2023-02-25 23:16
> An outside source claims that the issue is now fixed.

I can confirm it's working for me as well now. Thanks for fixing that so quick
